# Generated by Django 3.2.19 on 2023-06-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
